### ISSUE TITLE
Do not react with thumbs up if the command is invalid

### ISSUE THREAD

**Issue by danxuliu** [rullzer/backportbot#13]
For example, [when the mentioned branch does not exist](https://github.com/nextcloud/server/pull/12649)

**Comment by rullzer** [comment]
Right. So the thing is the +1 is added directly to tell you it is doing/will do something.

But we should have better error reporting I fully agree.

**Comment by skjnldsv** [comment]
The compile bot is adding a confused reaction if it does not understand of if it is invalid
